name: hacking_checklist
description: This is a flutter application which keep tracks of my hacking checklists.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  google_fonts: ^0.3.9
  sqflite: ^1.2.0
  path_provider: ^1.4.5
  path: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/file/checklist.txt
